### ISSUE TITLE
Support Swarm hashes

### ISSUE THREAD

**Issue by Arachnid** [pldespaigne/content-hash#16]
EIP 1577 now specifies how to encode Swarm hashes. Can you update the library to support encoding and decoding hashes in this format?

**Comment by pldespaigne** [comment]
I will do it ASAP !

**Comment by pldespaigne** [comment]
@Arachnid Those change have already been done by @nonsense [here](https://github.com/pldespaigne/content-hash/pull/14), but as said in the PR, I can't publish the package to npm for the moment, because npm js-multicodec and cids are not up to date with their github repo

https://github.com/multiformats/js-multicodec/issues/42
https://github.com/multiformats/js-cid/issues/85

**Comment by pldespaigne** [comment]
- [x] done in v2.3.1
